// colors

export const colorWhite = "#FFFFFF"
export const colorBlack = "#000000"
export const colorRed = "#F08A81"
export const redDarkOne = "#D76F66"
export const redDarkTwo = "#AD5E57"
export const redLightOne = "#FDC0BB"
export const redLightTwo = "#FFD6D2"
export const redLightThree = "#FFECEB"
export const colorBlue = "#98ECF0"
export const blueDarkOne = "#83D0D4"
export const blueDarkTwo = "#62A7AA"
export const blueLightOne = "#A4F6FA"
export const blueLightTwo = "#B4F8FB"
export const blueLightThree = "#D9FDFF"
export const colorGreen = "#98F0CA"
export const greenDarkOne = "#84D6B3"
export const greenDarkTwo = "#6DA98F"
export const greenLightOne = "#B1FFDD"
export const greenLightTwo = "#C3F9E2"
export const greenLightThree = "#E0FFF2"
export const colorGray = "#605B68"
export const grayDarkOne = "#413E46"
export const grayDarkTwo = "#323133"
export const grayLightOne = "#9A94A2"
export const grayLightTwo = "#CDC8D4"
export const grayLightThree = "#F8F4FF"

// spacers

export const spacer3XS = "9px"
export const spacer2XS = "12px"
export const spacerXS = "16px"
export const spacerS = "20px"
export const spacerM = "24px"
export const spacerL = "30px"
export const spacerXL = "38px"
export const spacer2XL = "46px"
export const spacer3XL = "60px"
export const spacer4XL = "74px"
export const spacer5XL = "90px"

// type

export const type3XS = "11px"
export const type2XS = "14px"
export const typeXS = "16px"
export const typeS = "20px"
export const typeM = "24px"
export const typeL = "28px"
export const typeXL = "34px"
export const type2XL = "40px"
export const type3XL = "50px"
export const type4XL = "60px"
export const type5XL = "72px"

export const sans = "Mark Pro"
export const serif = "Reckless Trial"
